### ISSUE TITLE
Is it possible to set APPLICATION_EXTENSION_API_ONLY to true?

### ISSUE THREAD

**Issue by mskrischke** [muxinc/mux-stats-sdk-avplayer#101]
Hello,

We are using version 2.4 of the SDK for our iOS and tvOS app. 

In our current setup, both apps share a dynamic framework that contains our shared video player and MUX bootstrap code next to other things. This dynamic framework is also a dependency for some of our application extensions (a Widget, a Notification Extension, and a Topshelf Provider) and therefore has the setting "Allow app extension API only" enabled.
The framework links against the MUX SDK.

When we build our app we see the following warning:

`Linking against a dylib which is not safe for use in application extensions: /...../Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/MUXSDKStats/MUXSDKStats.framework/MUXSDKStats`

which seems to be expected as the MUX SDK does not set the APPLICATION_EXTENSION_API_ONLY build setting. 

My question would be if there is a reason that the SDK can't be used from a framework that allows app extension API only ~~or if you would consider adding `s.pod_target_xcconfig = { 'APPLICATION_EXTENSION_API_ONLY' => 'YES' }` to both pod specs of the SDK~~?

Thanks and kind regards,
Markus

Edit: After more research it seems that the missing entry in the pod spec is not the reason for the warning. It seems the  precompiled binary in the SDK would need to be compiled with APPLICATION_EXTENSION_API_ONLY = YES to get rid of the warning. Can you please look into this?

**Comment by nidhik** [comment]
Hi @mskrischke!

We have set `APPLICATION_EXTENSION_API_ONLY = YES` in the latest releases. These are AVPlayer `v2.11.0` and Core Obj-c `v3.9.0`.

* https://github.com/muxinc/mux-stats-sdk-avplayer/releases/tag/v2.11.0
* https://github.com/muxinc/stats-sdk-objc/releases/tag/v3.9.0
