### ISSUE TITLE
Unable to commit Mux SDK to git repository after v2.2.0

### ISSUE THREAD

**Issue by crtgregoric** [muxinc/mux-stats-sdk-avplayer#107]
Since v2.2.0 (and up to the latest version) I started getting the following error when trying to commit the updated Mux SDK after performing `pod update`.

> fatal: pathspec 'Pods/Mux-Stats-Core/XCFramework/MuxCore.xcframework/ios-arm64_x86_64-maccatalyst/MuxCore.framework/Headers/MUXSDKAdBreakEndEvent.h' is beyond a symbolic link

#### Context:
- the Mux SDK is integrated via Cocoapods (`pod 'Mux-Stats-AVPlayer'`) and committed along with the project to our git repository
- up to v2.2.0 I was able to commit the Mux SDK to the repo after performing `pod update` but after updating to v2.2.0 I started getting the above error
- as a temporary workaround I locked the SDK version to v2.1.0 (`pod 'Mux-Stats-AVPlayer', '2.1.0'`) which can be committed but this is not an ideal solution since I cannot updated to the latest version

**Comment by nidhik** [comment]
Hi @crtgregoric! Thank you for reporting this issue. 

v2.2.0 introduced macOS Catalyst support which requires symlinks to work properly. Git should be able to handle symlinks, saving the relative path and the source files separately. However, we think in your case git is trying to directly access the contents "inside" `https://github.com/muxinc/mux-stats-sdk-avplayer/blob/master/XCFramework/MUXSDKStats.xcframework/ios-arm64_x86_64-maccatalyst/MUXSDKStats.framework/Headers` (which is actually symlink). 
Symlinks are transparent to some git client applications (are you using any in particular?) so sometimes will list files "inside" the symlink folder as changed files even though this is incorrect. 

What we would like to try is to commit the whole Pods folder without trying to target the specific contents. Git _should_ automatically identify the symlinks if you follow this process.

Could you please try the following steps to see if it resolves the issue?
* Remove the version lock in the podfile.
* `pod update Mux-Stats-AVPlayer`
* `git add Podfile Podfile.lock Pods`
* `git commit -m"Mux-Stats-AVPlayer update`

**Comment by crtgregoric** [comment]
Hi @nidhik, thanks for the above tips. Following your instructions and adding and committing the changes directly in cli worked without any issues. Usually I do use a git client. It's called Fork (https://git-fork.com).

Anyway the solution you provided worked, so this can be closed.

Thank you for the help!
