### ISSUE TITLE
Flaky SPM support - getting warnings which can be resolved by running"Clean build folder"

### ISSUE THREAD

**Issue by rist** [muxinc/mux-stats-sdk-avplayer#114]
When integrating MUX using SPM building and archiving often fails with 

```
/Users/rist/Library/Developer/Xcode/DerivedData/MUBI-hgzymitxhsmjdicobbmiajmcbaeq/SourcePackages/checkouts/mux-stats-sdk-avplayer/SwiftPM/MUXSDKStats.swift:5:8: error: no such module 'MuxCore'
import MuxCore
       ^
```

I can resolve that issue usually by running `Clean build folder` but definitely would feel more confident if this error wouldn't pop up.

**Comment by nidhik** [comment]
Hi @rist! Thank you for letting us know. We have not been able to reproduce this yet. We have tested on Xcode 12.5.1 and the project was able to build and run fine at first attempt without requiring an extra clean.

Could you please provide some additional details to help us reproduce the issue? What version of Xcode are you running? Do you see this specifically on archiving and with a release build configuration or on debug builds as well? Are there any special build steps or other context that might be relevant? Thank you.

**Comment by rist** [comment]
Hi

I switched to the most recent MUX release and Xcode 13 and it seems to work now - thanks
