### ISSUE TITLE
Installation using Carthage doesn't work. 

### ISSUE THREAD

**Issue by laxmorek** [muxinc/mux-stats-sdk-avplayer#123]
Hi 👋

### Short description 

I would like to add the `MuxStatsSDK` to my project using `Carthage`. I updated my `Cartfile` following [documentation](https://docs.mux.com/guides/data/monitor-avplayer#installing-manually-with-carthage-not-recommended) but installation fails when I run the `carthage update` command.

### Env

- Xcode - Version 13.1
- macOS - 12.0.1 (Monterey)
- mux-stats-sdk-avplayer - 2.6.0
- Carthage - 0.38.0
- Carthage command:
```
carthage update --platform iOS,tvOS --use-xcframeworks --no-use-binaries --use-netrc --cache-builds --new-resolver
```
- Cartage output (real paths has been hidden behind `[PATH]`):
```
*** Building scheme "MUXSDKStatsTv" in MUXSDKStats.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project [PATH]/Carthage/Checkouts/mux-stats-sdk-avplayer/MUXSDKStats/MUXSDKStats.xcodeproj -scheme MUXSDKStatsTv -configuration Release -derivedDataPath [PATH]/Library/Caches/org.carthage.CarthageKit/DerivedData/13.1_13A1030d/mux-stats-sdk-avplayer/v2.6.0 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/6q/ytvfydhj50d9jnbk76_zcq580000gp/T/mux-stats-sdk-avplayer SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in [PATH]/Carthage/Checkouts/mux-stats-sdk-avplayer)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6q/ytvfydhj50d9jnbk76_zcq580000gp/T/carthage-xcodebuild.SZZ0wZ.log
```

### Expected behavior 

I should be able to install the `MuxStatsSDK` using the `Carthage`.

**Comment by laxmorek** [comment]
It still occurs in `2.8.0`.

**Comment by laxmorek** [comment]
It still occurs in `2.9.0`.

**Comment by nidhik** [comment]
Hi @laxmorek! Thanks for reporting this issue and trying out the new release. If you use the binary specification in your Cartfile, does it work for you?

```
binary "https://raw.githubusercontent.com/muxinc/mux-stats-sdk-avplayer/master/MUXSDKStats.json"
binary "https://raw.githubusercontent.com/muxinc/stats-sdk-objc/master/MUXCore.json"
```

**Comment by laxmorek** [comment]
Hey @nidhik 👋 thanks for your answer. 

> If you use the binary specification in your Cartfile, does it work for you?

Yes it works! 🎉

Is it a preferable way to install MUX using Carthage?
-  If so we can close this issue. (PS. I would suggest updating docs [here](https://docs.mux.com/guides/data/monitor-avplayer#installing-manually-with-carthage-not-recommended)) 
- If you will be working on `github "muxinc/stats-sdk-objc" ~> 3.5.0` approach then lets keep this issue.

**Comment by nidhik** [comment]
@laxmorek great news! Yes, this will be the preferred way to install the Mux SDKs with Carthage going forward. I am working on the documentation updates and will keep this issue open until we have updated our official docs. Thank you!

**Comment by nidhik** [comment]
Closing now that the documentation has been updated with the preferred way to install using Carthage: https://docs.mux.com/guides/data/monitor-avplayer#installing-manually-with-carthage-not-recommended
