### ISSUE TITLE
Module 'GoogleInteractiveMediaAds' not found

### ISSUE THREAD

**Issue by nguyenquocdathcmus** [muxinc/mux-stats-sdk-avplayer#15]
To install with CocoaPods. I have error  "Module 'GoogleInteractiveMediaAds' not found". Can you help me?

**Comment by jsanford8** [comment]
Hi @nguyenquocdathcmus - thanks for reporting this. From this report, I'm guessing that you do not use Google's IMA SDK in your application. Is that correct?

In our recent release (0.1.4 and 0.1.5), we incorrectly included a dependency on Google's IMA SDK. We're working on fixing this, but for right now you can work around the issue by specifying (in your Podfile) `pod "Mux-Stats-AVPlayer", "0.1.3"` to lock to version 0.1.3.

**Comment by nguyenquocdathcmus** [comment]
@jsanford8  Thank you.  Perfect

**Comment by dylanjha** [comment]
For future reference, as of `1.0` (current release is `1.3.6`) `GoogleInteractiveMediaAds` is no longer a hard dependency. For use with GoogleInteractiveMediaAds we released a separate SDK:

https://github.com/muxinc/mux-stats-google-ima

More info in [the Mux AVPlayer docs](https://docs.mux.com/docs/avplayer-integration-guide#usage-with-google-interactive-media-ads-ima)
