### ISSUE TITLE
Integration via SPM in shared framework still broken?

### ISSUE THREAD

**Issue by rpitting** [muxinc/mux-stats-sdk-avplayer#154]
The installation instructions at https://docs.mux.com/guides/data/monitor-avplayer#1-install-the-mux-data-sdk state that due to an issue in Swift, MUX needs to be intregrated a .framework if using a shared framework.

However, the links to the corresponding Swift issues do not work anymore, as they are now hosted on Github and registration seems to be disabled anymore.

Is there still no chance to integrate MUX via SPM when using a shared framework?

**Comment by andrewjl-mux** [comment]
Hey @rpitting, apologies for the late reply. After testing with Xcode 14.3.1, we don't see build or code signing errors when integrating the SDK as a dependency of a shared framework package via Swift Package Manager.

We were able to build and run an app containing a shared framework wrapping the SDK installed [as a local package](https://developer.apple.com/documentation/xcode/editing-a-package-dependency-as-a-local-package) and [as a remote package](https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app#Add-a-package-dependency). We've also updated our [SDK documentation](https://docs.mux.com/guides/data/monitor-avplayer#installing-with-swiftpm) accordingly.

For reference, here's the contents of the `Package.swift` we tested with:

```
// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "mux-data-container",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "MuxDataContainer",
            targets: ["MuxDataContainer"]),
    ],
    dependencies: [
        .package(
            url: "https://github.com/muxinc/mux-stats-sdk-avplayer.git",
            branch: "master"
        )
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "MuxDataContainer",
            dependencies: [
                .product(
                    name: "MUXSDKStats",
                    package: "mux-stats-sdk-avplayer"
                )
            ]),
        .testTarget(
            name: "MuxDataContainerTests",
            dependencies: ["MuxDataContainer"]),
    ]
)
```
If you do run into any more issues with this approach, please let us know either here or via support@mux.com.

Closing this issue as it has been resolved.
