### ISSUE TITLE
3.2 release missing xcframeworks

### ISSUE THREAD

**Issue by gabors** [muxinc/mux-stats-sdk-avplayer#177]
Hi @daytime-em 

Were you planning making a 3.2 release with the static and dynamic xcframeworks?
So far I can only find 3.2 in the Tags but not in Releases.

Thanks!

**Comment by daytime-em** [comment]
Hi @gabors!

We are experiencing deployment issues, but the 3.2 update should be coming tomorrow, pacific time. Thank you for your patience!

**Comment by daytime-em** [comment]
Version [3.2.0](https://github.com/muxinc/mux-stats-sdk-avplayer/releases/tag/v3.2.0) has now been released. Thanks again for bearing with us!
