### ISSUE TITLE
Integration on YoutubePlayer

### ISSUE THREAD

**Issue by luchi17** [muxinc/mux-stats-sdk-avplayer#179]
Hey!
I was wondering if it is possible to track YouTube videos with this Mux SDK or another one.

Thanks in advance

**Comment by daytime-em** [comment]
Hello!

Unfortunately, we do not offer any direct support for tracking metrics from the YouTube players for either platform. You might be able to get enough information from the Youtube Helper library to create a [custom integration](https://docs.mux.com/guides/data/custom-objectivec-integration), but we don't offer any SDKs specifically for YouTube players.

Thank you for your interest
