### ISSUE TITLE
ensure update timer stops if app is backgrounded

### ISSUE THREAD

**Issue by theRealWardo** [muxinc/mux-stats-sdk-avplayer#19]
see the TODO at https://github.com/muxinc/mux-stats-sdk-avplayer/blob/master/MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m#L494

this may be the cause of us sometimes sending beacons while the app is in the background? we should make sure that if the user backgrounds the app and stops the player, then the SDK doesn't keep sending beacons.

**Comment by nidhik** [comment]
We have confirmed that the app does not continue to send beacons when terminated. We are not able to (at the SDK level) know if the app moves to the background state, so it is currently the responsibility of the application to destroy the monitor if necessary.
