### ISSUE TITLE
Xcode 15 linker warning: Duplicate LC_RPATH are deprecated

### ISSUE THREAD

**Issue by gabors** [muxinc/mux-stats-sdk-avplayer#197]
Starting with Xcode 15 adding dynamic MUXSDKStats.xcframework 3.3.1 to an iOS project as a dependency causes these linker warning to be emitted, can you please fix?

Duplicate LC_RPATH are deprecated ('@executable_path/Frameworks')
Duplicate LC_RPATH are deprecated ('@loader_path/Frameworks')

FWIW the MuxCore xcframework is fine.
Thanks!

**Comment by andrewjl-mux** [comment]
Hey @gabors, thank you for your report, are you installing MUXSDKStats.xcframework using a package manager or manually?

**Comment by gabors** [comment]
I'm installing manually.
Couple years ago we tried with your colleagues to install it using SPM but since I'm adding Mux to a shared framework that is used by two other executable targets it wasn't working.

**Comment by andrewjl-mux** [comment]
Got it! We'll work on removing this warning for manual installations.

Installing the SDK to a shared framework should be supported on Xcode 14+. Here's an example:

```swift
// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "mux-data-container",
    products: [
        .library(
            name: "MuxDataContainer",
            targets: ["MuxDataContainer"]),
    ],
    dependencies: [
        .package(
            url: "https://github.com/muxinc/mux-stats-sdk-avplayer.git",
            branch: "master"
        )
    ],
    targets: [
        .target(
            name: "MuxDataContainer",
            dependencies: [
                .product(
                    name: "MUXSDKStats",
                    package: "mux-stats-sdk-avplayer"
                )
            ]),
        .testTarget(
            name: "MuxDataContainerTests",
            dependencies: ["MuxDataContainer"]),
    ]
)
```

If you ever get a chance to try this again, let us know if you run into any issues. That is an installation method we intend to support for SPM.

I've added a separate issue #198 for adding an additional SPM example application to demonstrate this end-to-end.

**Comment by gabors** [comment]
@andrewjl-mux thank so much for your prompt replies.
I just tried to integrate Mux using SMP again (in Xcode 15 this time) to refresh my memory.
iOS and tvOS targets built and ran just fine.
It was the macCatalyst iOS flavour that is cause a crash on app launch:

`dyld[3504]: Library not loaded: @rpath/MUXSDKStats.framework/Versions/A/MUXSDKStats
  Referenced from: <56AB8882-AE76-3523-989D-D55C2E4BED9E> /Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/Frameworks/WBTVDKit.framework/Versions/A/WBTVDKit
  Reason: tried: '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/MUXSDKStats.framework/Versions/A/MUXSDKStats' (code signature in <42BDF9B2-DA60-38DD-83A6-09FDFC3D0BCA> '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/MUXSDKStats.framework/Versions/A/MUXSDKStats' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/PackageFrameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/usr/lib/swift/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/PackageFrameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/PackageFrameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/Frameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/Frameworks/WBTVDKit.framework/Versions/A/Frameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/usr/lib/swift/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/PackageFrameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/PackageFrameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/../Frameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/Frameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/usr/lib/swift/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/PackageFrameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/PackageFrameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/../Frameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file), '/Users/gabor/Library/Developer/Xcode/DerivedData/WBTVD-dvyuhesrwqbsdzgfpqdekcybxsmb/Build/Products/Debug-maccatalyst/WBDScreeners.app/Contents/MacOS/Frameworks/MUXSDKStats.framework/Versions/A/MUXSDKStats' (no such file)
Message from debugger: killed`

**Comment by gabors** [comment]
@andrewjl-mux I recall we worked with @daytime-em trying to find a solution without success, based on the error above is it some signing issue.
We also were wondering if Mux can be distributed using swift source instead of binary to work around this.

**Comment by andrewjl-mux** [comment]
Thank you, @gabors for sharing the crash report. We'll look into the mac catalyst crash separately. I may ping you on a separate issue thread about this, if that's ok.

We do plan to distribute `mux-stats-sdk-avplayer` as source and not as an xcframework but no timeline to share about when that'll be available yet. I can follow up with you when we have more on this.

**Comment by gabors** [comment]
@andrewjl-mux Awesome looking forward! Thanks again.

**Comment by gabors** [comment]
Hi @andrewjl-mux thanks for the great progress, MUXSDKStats 3.3.2 got rid of the `Duplicate LC_RPATH are deprecate` build warnings.

**Comment by andrewjl-mux** [comment]
Thank you @gabors for the fast followup, glad this was resolved.
