### ISSUE TITLE
Double check videoDataUpdated url logic

### ISSUE THREAD

**Issue by kcking** [muxinc/mux-stats-sdk-avplayer#24]
https://github.com/muxinc/mux-stats-sdk-avplayer/blob/master/MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m#L267
```
        if (!_videoURL || [_videoURL isEqualToString:urlString]) {
```
should probably be 
```
        if (!_videoURL || ![_videoURL isEqualToString:urlString]) {
```

**Comment by nidhik** [comment]
This is resolved: https://github.com/muxinc/mux-stats-sdk-avplayer/blob/994211cff82971df88eefd01ce022b6c1c5fe677/MUXSDKStats/MUXSDKStats/MUXSDKPlayerBinding.m#L486
