### ISSUE TITLE
macOS Catalyst support

### ISSUE THREAD

**Issue by mcmurrym** [muxinc/mux-stats-sdk-avplayer#51]
We are researching bring our iOS app to macOS via Catalyst. Can we get Catalyst support?

**Comment by jkrzemie** [comment]
Same here, would be great to get some info on this.

**Comment by dylanjha** [comment]
Interesting! This isn't something we have heard until now. Do you have an example app with a simple video player that we can take a look at and see about integrating? I assume Catalyst still uses `AVPlayerController` and `AVPlayerLayer`?

**Comment by mcmurrym** [comment]
This is Apples developer resource start page for macOS Catalyst. https://developer.apple.com/documentation/uikit/mac_catalyst. Because this is a framework most of the contents do not apply.

As a quick brief you ship your iOS mac as a mac App, so yes `AVPlayerViewController` and `AVPLayerLayer` are used.

For mux to work with macOS Catalyst you'll likely need to do three things:
1.) Adjust the project settings in this repo to support macOS Catalyst
2.) Update the binary `MUXSDKStats` in the iOS section to include architecture for macOS Catalyst.
3.) Maybe, but maybe not, re-configure the Podspec (and maybe Carthage) to support catalyst.

I assume that because you're aware of how to compile the binary for iOS it should be fairly simple. This forum post explains the architecture and variant parameters for building for Catalyst. https://forums.developer.apple.com/thread/120542

**Comment by dylanjha** [comment]
@mcmurrym thank you for these details, that is very helpful!

**Comment by tfe** [comment]
We're also looking to ship a Mac Catalyst build of an existing iOS app, but would have to remove the Mux Data SDK in order to do so. Do you have any plans to support this?

**Comment by dylanjha** [comment]
hi @tfe Mac Catalyst support was added as of [v2.0.0 when we moved to XCFramework](https://github.com/muxinc/mux-stats-sdk-avplayer/releases/tag/v2.0.0) and then a code signing issue specific to Mac Catalyst was fixed in [v2.2.2](https://github.com/muxinc/mux-stats-sdk-avplayer/releases/tag/v2.2.2).

Could you give it a try? Also, SPM support was added so if you use SPM as a package manager you can install from there!

**Comment by tfe** [comment]
Oh excellent, I'll check that out!

**Comment by nidhik** [comment]
Closing, as Mac Catalyst support was added as of `v2.0.0`
