### ISSUE TITLE
No Support for CocoaPods CDN

### ISSUE THREAD

**Issue by rpitting** [muxinc/mux-stats-sdk-avplayer#52]
It seems as the Mux CocoaPod is not available via the CocoaPods CDN:

Podfile:
```ruby
require 'fileutils'

#source 'https://cdn.cocoapods.org/'

# Target def etc....
pod 'Mux-Stats-AVPlayer', '~> 1.3.6'
```

results in:
```
Analyzing dependencies
[!] Unable to find a specification for `Mux-Stats-AVPlayer (~> 1.3.6)`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Adding `source 'https://github.com/CocoaPods/Specs.git'` seems to solve the problem, but this leads to cloning the entire CocoaPods master repo, which is deprecated since [CocoaPods 1.8](http://blog.cocoapods.org/CocoaPods-1.8.0-beta/).

**Comment by dylanjha** [comment]
@rpitting this should be available on Cocoapods: https://cocoapods.org/pods/Mux-Stats-AVPlayer

Earlier today I was getting a 503 error from Cocoapods, with every pod I tried:

```
❯ curl -I "https://cocoapods.org/pods/Alamofire"
HTTP/2 503
date: Mon, 15 Jun 2020 14:43:42 GMT
set-cookie: __cfduid=d24d0b877cf593696a0eea1cb1b04a5001592232222; expires=Wed, 15-Jul-20 14:43:42 GMT; path=/; domain=.cocoapods.org; HttpOnly; SameSite=Lax
via: 1.1 vegur
cf-cache-status: DYNAMIC
cf-request-id: 035a08b8460000ebdd90995200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5a3d10a07bc5ebdd-LAX
```

Seems to be working now though, can you try again and let me know? Thanks!

**Comment by rpitting** [comment]
Sorry for the false alarm, seem's to work now. Thanks for taking time anyways!
