### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by cerupcat** [muxinc/mux-stats-sdk-avplayer#72]
Is SPM support on the roadmap?

**Comment by bkobilansky** [comment]
Howdy all!

I did some experimenting on consuming Mux from Swift Package Manager for a project I work on; I am not 100% confident that this is correct, but I was able to get a compiling and executing package by using [the .xcframework embedded in this repo](https://github.com/muxinc/mux-stats-sdk-avplayer/tree/master/XCFramework/MUXSDKStats.xcframework) and the [.xcframework from Core](https://github.com/muxinc/stats-sdk-objc/tree/master/XCFramework/MuxCore.xcframework), and setting up this Package.swift:

```Swift
let package = Package(
  name: "Mux",
  products: [ .library(name: "Mux", targets: ["Mux", "MuxCore"]), ],
  dependencies: [],
  targets: [
    .binaryTarget(name: "Mux", path: "MUXSDKStats.xcframework"),
    .binaryTarget(name: "MuxCore", path: "MuxCore.xcframework"),
  ]
)
```

...this assumes the two .xcframeworks are in the root of the package directory, right next to the Package.swift file.

cc @cerupcat, hopefully this helps if you need to use this via SPM.

**Comment by cerupcat** [comment]
Nice! I wonder if we can put up a PR for this with the paths to the GitHub xcframeworks

**Comment by richard-ash** [comment]
+1 let's make this a PR!

**Comment by gabors** [comment]
Agreed!

**Comment by AndrewBarba** [comment]
Here we go: https://github.com/muxinc/mux-stats-sdk-avplayer/pull/84

**Comment by MohammedBadr20s** [comment]
@AndrewBarba so for this change we should use master branch instead of latest version alright ?

**Comment by nidhik** [comment]
SPM support was added in the following releases:
* https://github.com/muxinc/stats-sdk-objc/releases/tag/v3.2.0
* https://github.com/muxinc/mux-stats-sdk-avplayer/releases/tag/v2.2.0
