### ISSUE TITLE
Unable to integrate via Cocoapods

### ISSUE THREAD

**Issue by cerupcat** [muxinc/mux-stats-sdk-avplayer#73]
When adding via cocoapods, I get the following error:

`ld: building for iOS, but linking in dylib file (<path>/DerivedData/App/Build/Products/Debug-iphoneos/MUXSDKStats.framework/MUXSDKStats) built for Mac Catalyst, file '/<path>/DerivedData/App/Build/Products/Debug-iphoneos/MUXSDKStats.framework/MUXSDKStats' for architecture arm64`

I don't have Mac Catalyst integrated, so I don't know why it's being referenced.

**Comment by dylanjha** [comment]
Hi @cerupcat thanks for surfacing. 

If you're installing version 3.x that is built for XCode 12. Are you running on XCode 12?

**Comment by cerupcat** [comment]
Thanks, yes. I'm using Xcode 12.3 with:

`pod 'Mux-Stats-AVPlayer', '~>2.0.0'`

I've tried cleaning, updating pod, etc and the same error persists.

**Comment by cerupcat** [comment]
Just updated to the latest version of cocoapods and it works now. Looks like the latest version requires CocoaPods 1.10.0+.

**Comment by dylanjha** [comment]
That will do it! Thanks @cerupcat !
