### ISSUE TITLE
Carthage support for XCframework

### ISSUE THREAD

**Issue by agruchala** [muxinc/mux-stats-sdk-avplayer#81]
```
*** Skipped building mux-stats-sdk-avplayer due to the error:
Dependency "mux-stats-sdk-avplayer" has no shared framework schemes for any of the platforms: iOS, tvOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/muxinc/mux-stats-sdk-avplayer/issues/new
```
We can't use Carthage with xcframeworks right now, can You add json file to repo for binary support or configure carthage support with xcframework? SPM will be awesome too.

**Comment by pepasibble** [comment]
I just ran into this as well -- Carthage isn't working.

**Comment by dylanjha** [comment]
Hi @agruchala @pepasibble. Carthage by default is not compatible with XCode 12 (Our XCFramework builds require XCode 12+).

This is a recommended workaround: https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

**Comment by pepasibble** [comment]
Hi @dylanjha , as of Carthage 0.37 you can use the `--use-xcframeworks` option, but this seems unrelated to the `has no shared framework schemes` error.

**Comment by dylanjha** [comment]
@pepasibble hmm, interesting. Okay so now that Carthage supports xcframeworks, are you also able to get Carthage working with XCode 12? (either with the workaround, or another method?)

If you could provide repro steps that would be helpful. Then I can put this on the team's radar to take a look.

Also @agruchala I see you asked for SPM before in the original issue. That is available now!

**Comment by pepasibble** [comment]
Here are the repro steps:
- Create a new Xcode project
- Create a Cartfile with `github "muxinc/mux-stats-sdk-avplayer" == 2.2.1`
- Run `carthage bootstrap --use-xcframeworks --platform iOS`

You will see this output:

```
$ carthage bootstrap --use-xcframeworks --platform iOS
*** No Cartfile.resolved found, updating dependencies
*** Fetching mux-stats-sdk-avplayer
*** Checking out mux-stats-sdk-avplayer at "v2.2.1"
*** xcodebuild output can be found in /var/folders/sh/ps9bnm5s4ll_r12k00tczl_c0000gn/T/carthage-xcodebuild.DJTkUN.log
*** Downloading mux-stats-sdk-avplayer.framework binary at "v2.2.1"
*** Skipped building mux-stats-sdk-avplayer due to the error:
Dependency "mux-stats-sdk-avplayer" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/muxinc/mux-stats-sdk-avplayer/issues/new
```

**Comment by nidhik** [comment]
Hi @agruchala @pepasibble

It is now possible to use Carthage with XCFrameworks. We have updated the required steps for installing the Mux SDKs via Carthage. Please let us know if this works for you. https://docs.mux.com/guides/data/monitor-avplayer#installing-manually-with-carthage-not-recommended

**Comment by daytime-em** [comment]
Closing due to age, Carthage is still working fine
