### ISSUE TITLE
Hitting a crash when stopping then later using an AVPlayer again

### ISSUE THREAD

**Issue by pepasibble** [muxinc/mux-stats-sdk-avplayer#93]
When I added mux data to my app, I immediately started getting crashes which seemed to be related to removing KVO observers:

![Screen Shot 2021-04-20 at 8 08 25 PM](https://user-images.githubusercontent.com/78579108/116469338-a6339c80-a837-11eb-9ea4-1fedbd74ae5d.png)

This seems to be happening when stop using a player and then later start using it again.

When I start the player, I call `monitorAVPlayerLayer()`:

![Screen Shot 2021-04-28 at 3 39 26 PM](https://user-images.githubusercontent.com/78579108/116469757-2823c580-a838-11eb-92ef-34f8282aad3d.png)

When I stop using the player, I call `destroyPlayer()`:

![Screen Shot 2021-04-28 at 3 39 34 PM](https://user-images.githubusercontent.com/78579108/116469780-2f4ad380-a838-11eb-9bef-45e916d5ba2c.png)

Perhaps I am using the SDK incorrectly?

**Comment by dylanjha** [comment]
Hey @pepasibble quick question. It sounds like you are re-using the same `AVPlayerLayer` instance for multiple view, correct? At what point are you calling `destroyPlayer()`, is that between the two views, or after all the views are done?

It would be great if you could provide more details about the flow going on there, specifically around when the AVPlayerLayer is initialized, when the source is changing and when `destroyPlayer` is being called

**Comment by pepasibble** [comment]
Yes, that's correct, I have a long-lived AVPlayerLayer, and am going through multiple rounds of `monitorAVPlayerLayer` / `destroyPlayer` on that player.

**Comment by dylanjha** [comment]
Got it, you shouldn't need to keep doing `monitorAVPlayerLayer` and `destroyPlayer` on every new video. I think that's the problem.

Can you try something more like the following:

* `monitorAVPlayerLayer` once when the instance is initialized
* when you change the video source use `videoChange` to let the monitor know - and you can pass in new `videoData` at that point in time `MUXSDKStats.videoChange(forPlayer: "AVPlayer", with: videoData)`
* when you're entirely done with the `AVPlayerLayer` instance and not using it anymore, then you can `destroyPlayer`

One caveat is that *after* you call `MUXSDKStats.videoChange` you will have to call `player.play()` on the player instance for the new view to be tracked correctly.

Let me know if that helps

**Comment by pepasibble** [comment]
Is this SKD making any assumptions about the relationship between a layer and a player?  Those two objects have different life cycles in my app.

**Comment by dylanjha** [comment]
@pepasibble good question. The answer is not really. The `AVPlayerLayer` instance is really only used to get the dimensions of the view. Dimensions of the view compared to the dimensions of the underlying video source is how upscale % and downscale % is calculated.

Everything else is based off observing `AVPlayer` lifecycle events, KVOs, playhead position, etc. The `AVPlayerLayer` instance isn't used for that stuff.

**Comment by pepasibble** [comment]
Ok, taking another look at this, it looks like `videoData` is nullable on `monitorAVPlayerLayer`, so I can call `monitorAVPlayerLayer` once upon player creation and `destroyPlayer` when the player is about to be deallocated.

Separately, I can use `videoChangeForPlayer` when a particular video starts / stops, because `videoData` is also nullable there as well.

I'll give that a shot.

**Comment by pepasibble** [comment]
One other question:

```
// Use this method to modify the AVPlayerLayer a Mux player monitor is watching.
+ (void)updateAVPlayerLayer:(nonnull AVPlayerLayer *)player withPlayerName:(nonnull NSString *)name;
```

It isn't clear what this function does.

It sounds like I'm supposed to call this function if I want this function to modify the layer for me.  But what modifications will it perform?  Why would I want this?

**Comment by dylanjha** [comment]
Yeah, you shouldn't have to use that `updateAVPlayerLayer` method. I would have to double check, but I think it's for an edge case if you remove your avPlayer instance from the layer attach it to a different layer.

**Comment by pepasibble** [comment]
Hey @dylanjha , this approach seems to be working with no crashes.  Thanks.

**Comment by dylanjha** [comment]
Fantastic @pepasibble, thanks for closing. Please let us know if anything else comes up
